locals {
  # One authoritative list of lab nodes. Ansible's inventory is generated from it.
  nodes = {
    "slurm-ctl" = { vmid = 130, ip = "10.0.5.130", cores = 2, memory = 3072, disk = 30, group = "slurm_controller" }
    "slurm-c1"  = { vmid = 131, ip = "10.0.5.131", cores = 2, memory = 2048, disk = 20, group = "slurm_compute" }
    "slurm-c2"  = { vmid = 132, ip = "10.0.5.132", cores = 2, memory = 2048, disk = 20, group = "slurm_compute" }
    "k8s-cp"    = { vmid = 133, ip = "10.0.5.133", cores = 4, memory = 6144, disk = 40, group = "k8s_control_plane" }
    "k8s-w1"    = { vmid = 134, ip = "10.0.5.134", cores = 4, memory = 8192, disk = 40, group = "k8s_workers" }
    "k8s-w2"    = { vmid = 135, ip = "10.0.5.135", cores = 4, memory = 8192, disk = 40, group = "k8s_workers" }
  }

  enabled_nodes = {
    for name, n in local.nodes : name => n
    if(startswith(n.group, "slurm_") && var.enable_slurm) || (startswith(n.group, "k8s_") && var.enable_k8s)
  }
}

resource "proxmox_virtual_environment_vm" "node" {
  for_each = local.enabled_nodes

  name        = each.key
  vm_id       = each.value.vmid
  node_name   = var.node_name
  pool_id     = var.pool_id
  description = "slurm-k8s-lab (${each.value.group}). Managed by Terraform; disposable. Never host live services here."
  tags        = ["lab", split("_", each.value.group)[0]]

  started = var.started
  on_boot = false # the lab never auto-starts with rogue

  machine       = "q35"
  scsi_hardware = "virtio-scsi-single"

  # No guest agent: Terraform would block waiting for it on first boot,
  # and IPs are static anyway.
  agent {
    enabled = false
  }

  cpu {
    cores = each.value.cores
    type  = "host"
  }

  memory {
    dedicated = each.value.memory
    floating  = 0 # no ballooning; kubelet and slurmd both want stable RealMemory
  }

  # Full clone of the Debian 13 template built by scripts/proxmox-bootstrap.sh.
  clone {
    vm_id = var.template_vmid
    full  = true
  }

  # Resizes the template's 3 GB disk (grow only).
  disk {
    datastore_id = var.vm_datastore
    interface    = "virtio0"
    size         = each.value.disk
    discard      = "on"
    iothread     = true
  }

  network_device {
    bridge = var.network_bridge
    model  = "virtio"
  }

  operating_system {
    type = "l26"
  }

  # Debian cloud images log to the serial console.
  serial_device {}

  initialization {
    datastore_id = var.vm_datastore
    interface    = "ide2"

    ip_config {
      ipv4 {
        address = "${each.value.ip}/${var.network_prefix}"
        gateway = var.gateway
      }
    }

    dns {
      servers = var.dns_servers
      domain  = var.dns_domain
    }

    user_account {
      username = var.admin_user
      keys     = var.ssh_public_keys
    }
  }
}

locals {
  groups = distinct([for n in values(local.enabled_nodes) : n.group])

  inventory = {
    all = {
      vars = {
        ansible_user               = var.admin_user
        ansible_python_interpreter = "/usr/bin/python3"
      }
      children = merge(
        {
          for g in local.groups : g => {
            hosts = { for name, n in local.enabled_nodes : name => { ansible_host = n.ip } if n.group == g }
          }
        },
        {
          slurm = { children = { for g in local.groups : g => {} if startswith(g, "slurm_") } }
          k8s   = { children = { for g in local.groups : g => {} if startswith(g, "k8s_") } }
        }
      )
    }
  }
}

resource "local_file" "ansible_inventory" {
  filename        = "${path.module}/../ansible/inventory/hosts.yml"
  content         = "# Generated by terraform/main.tf. Do not edit by hand.\n${yamlencode(local.inventory)}"
  file_permission = "0644"
}
